Employees/Controllers/LaborsController.cs
using Employees.Models;
using Employees.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Employees.Models.Dto;

namespace Employees.Controllers
{
    public class LaborsController : Controller
    {
        private LaborsService _laborsService;
        private UserManager<EmployeeUser> _userManager;

        private EmployeeUser CurrentUser
        {
            get { return _userManager.GetUserAsync(HttpContext.User).Result; }
        }

        public LaborsController(LaborsService _laborsService, UserManager<EmployeeUser> _userManager)
        {
            this._laborsService = _laborsService;
            this._userManager = _userManager;
        }

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        //[Authorize]
        //public ActionResult Details(long id)
        //{
        //    return View("Details", id);
        //}

        //[Authorize]
        //public ActionResult Edit(long id)
        //{
        //    return View("Edit", id);
        //}

        public List<LaborDto> GetAll(DateTime? startDate = null, DateTime? endDate = null)
        {
            return _laborsService.GetAll(startDate, endDate);
        }

        public List<LaborDto> GetAllMine(DateTime? startDate = null, DateTime? endDate = null)
        {
            return _laborsService.GetAllByUser(CurrentUser.Id, startDate, endDate);
        }

        public List<LaborsGroupByUser> GetByProject( long projectId,DateTime? startDate = null, DateTime? endDate = null)
        {
            return _laborsService.GetByProject(projectId, startDate, endDate);
        }

        public List<LaborDto> GetAllMyProjects(DateTime? startDate = null, DateTime? endDate = null)
        {
            return _laborsService.GetAllMyProjects(CurrentUser.Id, startDate, endDate);
        }

        public LaborDto Get(long id)
        {
            return _laborsService.Get(id,CurrentUser.Id,CurrentUser.FIO);
        }

        [HttpPost]
        public LaborDto Add([FromBody] LaborDto dto)
        {
            return _laborsService.Add(dto);
        }

        public LaborDto Delete(long id)
        {
            return _laborsService.Delete(id);
        }

        [HttpPost]
        public LaborDto Update([FromBody] LaborDto dto)
        {
            return _laborsService.Update(dto);
        }

        public bool CanEditLabor(long id)
        {
            return _laborsService.CanEditLabor(id, _userManager.GetRolesAsync(CurrentUser).Result.ToList(), CurrentUser.Id);
        }
        
        public List<EnumDto> GetAllTypes()
        {
            return _laborsService.GetAllTypes();
        }

        public List<EnumDto> GetAllPrioritys()
        {
            return _laborsService.GetAllPrioritys();
        }
    }
}

Employees/Controllers/PositionController.cs
using Employees.Data;
using Employees.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Employees.Controllers
{
    public class PositionController: Controller
    {
        private ApplicationDbContext _context;
        public PositionController(ApplicationDbContext _context)
        {
            this._context = _context;
        }

        [Authorize(Roles = RolesNames.Admin)]
        public ActionResult Index()
        {
            return View();
        }

        public List<Position> GetAll()
        {
            return _context.Positions.ToList();
        }

        [HttpPost]
        public Position Add([FromBody]Position position)
        {
            position.Id = 0;
            _context.Positions.Add(position);
            _context.SaveChanges();
            return position;
        }

        public Position Delete(long id)
        {
            Position deleted = _context.Positions.FirstOrDefault(x => x.Id == id);
            if (deleted == null)
                return null;

            _context.Positions.Remove(deleted);
            _context.SaveChanges();
            return deleted;
        }

        [HttpPost]
        public Position Update([FromBody]Position position)
        {
            _context.Positions.Update(position);
            _context.SaveChanges();
            return position;
        }
    }
}

Employees/Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Employees.Services;
using Microsoft.AspNetCore.Identity;
using Employees.Models;
using Employees.Models.Dto;
using Microsoft.AspNetCore.Authorization;

namespace Employees.Controllers
{
    public class ProjectsController: Controller
    {
        private ProjectService _projectService;
        private UserManager<EmployeeUser> _userManager;

        private EmployeeUser CurrentUser => _userManager.GetUserAsync(HttpContext.User).Result;

        public ProjectsController(ProjectService _projectService, UserManager<EmployeeUser> _userManager)
        {
            this._projectService = _projectService;
            this._userManager = _userManager;
        }

        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult Details(long id)
        {
            return View("Details", id);
        }

        [Authorize]
        public ActionResult Edit(long id)
        {
            return View("Edit", id);
        }

        public List<ProjectDto> GetAll()
        {
            return _projectService.GetAll();
        }

        public List<ProjectDto> GetAllMine()
        {
            return _projectService.GetAllByUser(CurrentUser.Id);
        }

        public ProjectDto Get(long id)
        {
            return _projectService.Get(id);
        }

        [HttpPost]
        public ProjectDto Add([FromBody]ProjectDto dto)
        {
            return _projectService.Add(dto);
        }

        public ProjectDto Delete(long id)
        {
            return _projectService.Delete(id);
        }

        [HttpPost]
        public ProjectDto Update([FromBody]ProjectDto dto)
        {
            return _projectService.Update(dto);
        }

        public bool ListReadonly()
        {
            return !_userManager.IsInRoleAsync(CurrentUser, RolesNames.Admin).Result;
        }

        public bool CanEditProject(long id)
        {
            return _projectService.CanEditProject(id,_userManager.GetRolesAsync(CurrentUser).Result.ToList(), CurrentUser.Id);
        }

        public List<EmployeeUserDto> GetProjectUsers(long id)
        {
            return _projectService.GetProjectUsers(id);
        }
        public List<ProjectDto> GetProjectByManager(string id)
        {
            return _projectService.GetProjectByManager(id);
        }

        public List<EmployeeUserDto> GetUsersToChoose(long id)
        {
            return _projectService.GetUsersToChoose(id);
        }

        public void RemoveFromProject(string employeeId, long projectId)
        {
            _projectService.RemoveFromProject(employeeId,projectId);
        }
        
        [HttpPost]
        public void AddUsersToProject(long projectId, [FromBody]List<string> userIds)
        {
            _projectService.AddUsersToProject(projectId, userIds);
        }
    }
}

Employees/Controllers/ReportsController.cs
using Employees.Models;
using Employees.Models.Dto;
using Employees.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;

namespace Employees.Controllers
{
    public class ReportsController : Controller
    {
        private ReportsService _reportsService;
        private UserManager<EmployeeUser> _userManager;
        private EmployeeUsersService _employeeService;

        private EmployeeUser CurrentUser => _userManager.GetUserAsync(HttpContext.User).Result;

        public ReportsController(ReportsService _reportsService, UserManager<EmployeeUser> _userManager, EmployeeUsersService _employeeService)
        {
            this._reportsService = _reportsService;
            this._userManager = _userManager;
            this._employeeService = _employeeService;
        }

        public DataTable GetReportTable(ReportSettings reportSettings)
        {
            return _reportsService.GetReportTable(reportSettings);
        }

        [Authorize]
        public ActionResult Analitics() => View();

        [Authorize]
        public ActionResult Finance() => View();

        [HttpPost]
        public IActionResult ExportPdf([FromBody]ReportSettings settings)
        {
            return File(_reportsService.ExportPDF(settings), "application/pdf");
        }

        [HttpPost]
        public IActionResult ExportSalaryPdf([FromBody]ReportSettings settings)
        {
            return File(_reportsService.ExportSalaryPdf(settings), "application/pdf");
        }

        [HttpPost]
        public IActionResult ExportExcel([FromBody]ReportSettings settings)
        {
            return File(_reportsService.ExportExcel(settings), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
        }

        public List<EmployeeUserDto> GetUsersWithEmails()
        {
            return _employeeService.GetUsersWithEmails();
        }

        [HttpPost]
        public ActionResult SendMails([FromBody]EmailSendDto emailSendDto)
        {
            string error = "";
            if(_reportsService.SendMails(emailSendDto, out error))
            {
                return Ok();
            }
            else
            {
                return new JsonResult(new { error });
            }
        }
    }
}

Employees/Views/Shared/_Layout.cshtml
@using Employees.Services
@using Microsoft.AspNetCore.Identity
@inject SignInManager<EmployeeUser> SignInManager
@inject UserManager<EmployeeUser> UserManager
@inject NotificationsService NotificationsService

<!DOCTYPE html>
<html lang="ru">
<head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/fontawesome/css/all.min.css" />
    <link href="~/css/minty.css" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="~/css/bootstrap-vue.css" />
    <link rel="stylesheet" href="~/css/vue-select.css" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">СУРС</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @*<partial name="_LoginPartial" />*@

                    <ul class="navbar-nav">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/ChangePassword" title="Управление">@Html.Raw(("Привет")) @User.Identity.Name!</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                    <button type="submit" class="nav-link btn btn-link text-dark">Выйти</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Войти</a>
                            </li>
                        }
                    </ul>

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Сотрудники</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Projects" asp-action="Index">Проекты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TaskModels" asp-action="Index">Задачи</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Labors" asp-action="Index">Трудозатраты</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Отчеты
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Reports" asp-action="Analitics">Аналитика</a></li>
                                <li> <a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Reports" asp-action="Finance">Финансы</a></li>
                            </ul>
                        </li>
                        @{
                            var user = UserManager.GetUserAsync(User).Result;
                        }
                        @if (user != null && UserManager.IsInRoleAsync(user, RolesNames.Admin).Result)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Настройки
                                </a>
                                <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="Position" asp-action="Index">Должности</a></li>
                                    <li><a class="nav-link text-dark dropdown-item" asp-area="" asp-controller="BonusSettings" asp-action="Index">Ставки премирования</a></li>
                                </ul>
                            </li>
                        }
                    @if (user != null)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notifications" asp-action="Index">
                                <i class="fas fa-exclamation-circle" style="font-size: 22px;@(NotificationsService.HasNew(user.Id) ? " color:#f57965; " : "")"></i>
                            </a>
                        </li>
                    }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container" style="margin-bottom: 60px">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - УлГТУ
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    <script src="~/js/vuex.js"></script>
    <script src="~/js/bootstrap-vue.js"></script>
    <script src="~/js/axios.js"></script>
    <script src="~/js/vue2-datepicker.js"></script>
    <script src="~/js/vue-select.js"></script>
    <script src="~/js/moment.js"></script>



    @RenderSection("Scripts", required: false)
</body>
</html>